version: '2'
services:
  web: 
    build: .
    image: rkoron/simple_node
    ports: 
      - 80:3000
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
    environment:
      - DATABASE_URL = postgres://postgres:password@db:5432/postgresdb
      - PORT=3000
  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresdb
      DB_HOST: db